// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
    'aws_app_analytics': 'enable',
    'aws_cognito_identity_pool_id': 'us-east-1:37d2a195-913f-45a1-a4e9-732443713d6e',
    'aws_cognito_region': 'us-east-1',
    'aws_content_delivery': 'enable',
    'aws_content_delivery_bucket': 'creations-hosting-mobilehub-359791838',
    'aws_content_delivery_bucket_region': 'us-east-1',
    'aws_content_delivery_cloudfront': 'enable',
    'aws_content_delivery_cloudfront_domain': 'd1kp89vnzqbpcy.cloudfront.net',
    'aws_mobile_analytics_app_id': '659e7997acc4495fa50bea62a17d118c',
    'aws_mobile_analytics_app_region': 'us-east-1',
    'aws_project_id': 'b6397f08-e342-4efb-a351-a1eb392a9199',
    'aws_project_name': 'creations',
    'aws_project_region': 'us-east-1',
    'aws_resource_name_prefix': 'creations-mobilehub-359791838',
}

export default awsmobile;
